import type { Metadata } from "next";
import { Geist, Geist_Mono , Zen_Dots, Montserrat } from "next/font/google";
import 'boxicons/css/boxicons.min.css';
import "./globals.css";
import Header from "@/components/header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const zenDots = Zen_Dots({
  weight: "400",
  variable: "--zen-dots",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: "400",
  variable: "--montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vinit Khollam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${zenDots.variable} ${montserrat} antialiased bg-black`}
      >
        <Header />
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
